/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import admin.adminDB;
import config.connectDB;
import config.session;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vienz
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
     Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
    Color charcoal = new Color(28, 28, 28);
    Color teal = new Color(0, 128, 128);

    
    
    public String[] loginAcc(String email, String password) {

        connectDB con = new connectDB();

        try {
            String query = "SELECT * FROM user WHERE u_email = ? AND u_password = ?";
            PreparedStatement pstmt = con.getConnection().prepareStatement(query);
            pstmt.setString(1, email.trim());
            pstmt.setString(2, password.trim());
            ResultSet resultSet = pstmt.executeQuery();

            if (resultSet.next()) {
                return new String[]{resultSet.getString("u_type").trim(), resultSet.getString("u_status")};
            }

        } catch (SQLException ex) {

        }
        return null;
    }
    
    public String[] getUserDetails(String email) {
    connectDB con = new connectDB();
    try {
        String query = "SELECT u_id, u_firstname, u_lastname, u_email, u_contactnumber, u_type, u_status FROM user WHERE u_email = ?";
        PreparedStatement pstmt = con.getConnection().prepareStatement(query);
        pstmt.setString(1, email.trim()); // Set email as the query parameter
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            return new String[]{
                resultSet.getString("u_id").trim(),
                resultSet.getString("u_firstname").trim(),
                resultSet.getString("u_lastname").trim(),
                resultSet.getString("u_email").trim(),
                resultSet.getString("u_contactnumber").trim(),
                resultSet.getString("u_type").trim(),
                resultSet.getString("u_status").trim()
            };
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return null; // Return null if no user is found
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        logintext = new javax.swing.JLabel();
        registerbutton = new javax.swing.JLabel();
        forgotpassword = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        passtext = new javax.swing.JLabel();
        requireduser = new javax.swing.JLabel();
        requiredpass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 240, 36));

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 240, 36));

        logintext.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logintext.setForeground(new java.awt.Color(173, 216, 230));
        logintext.setText("Login");
        jPanel2.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        registerbutton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(0, 153, 153));
        registerbutton.setText(" Register here");
        registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuttonMouseClicked(evt);
            }
        });
        jPanel2.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        forgotpassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        forgotpassword.setText("Forgot password");
        jPanel2.add(forgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, -1));

        emailtext.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        emailtext.setText("Email");
        jPanel2.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        passtext.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        passtext.setText("Password");
        jPanel2.add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));
        jPanel2.add(requireduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 240, 10));
        jPanel2.add(requiredpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 240, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Don't have an account?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        login.setBackground(new java.awt.Color(173, 216, 230));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Login");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 2, -1, -1));

        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 100, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 460, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        Font smallFont = new Font("Arial", Font.PLAIN, 10); 
username.setFont(smallFont); 
requireduser.setFont(smallFont); 

String user = username.getText();

if (user.isEmpty()) {
    username.setForeground(Color.RED);
    requireduser.setText("Username is required");
    requireduser.setForeground(Color.RED);
} else {
    username.setForeground(Color.BLACK);
    requireduser.setText("");
}

username.repaint();
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
Font smallFont = new Font("Arial", Font.PLAIN, 10);
password.setFont(smallFont); 
requiredpass.setFont(smallFont); 

String user = password.getText();

if (user.isEmpty()) {
    password.setForeground(Color.RED);
    requiredpass.setText("Password is required");
    requiredpass.setForeground(Color.RED);
} else {
    username.setForeground(Color.BLACK);
    requiredpass.setText("");
}

password.repaint();
    }//GEN-LAST:event_passwordFocusLost

    private void registerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseClicked
        register reg = new register();

        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerbuttonMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
      String user = username.getText().trim();
String pass = password.getText().trim();

if (user.isEmpty() || pass.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Username and/or password cannot be empty.", "Login Error", JOptionPane.ERROR_MESSAGE);
    username.requestFocus();
    return;
}

try {
    // Directly use the entered username and password without hashing
    String[] loginData = loginAcc(user, pass);

    if (loginData == null) {
        JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        password.requestFocus();
        return;
    }

    String[] userDetails = getUserDetails(user);

    String userID = userDetails[0];
    String firstName = userDetails[1];
    String lastName = userDetails[2];
    String email = userDetails[3];
    String contactNumber = userDetails[4];
    String accType = loginData[0];
    String accStatus = loginData[1];

    if (!"active".equalsIgnoreCase(accStatus)) {
        JOptionPane.showMessageDialog(this, "Your account is still pending. Please contact the administrator.", "Login Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    session sess = session.getInstance();
    sess.setU_id(userID);
    sess.setUsername(user);
    sess.setFirstName(firstName);
    sess.setLastName(lastName);
    sess.setEmail(email);
    sess.setContact(contactNumber);
    sess.setAcc_type(accType);
    sess.setAcc_status(accStatus);

    if (accType != null) {
        if ("Admin".equalsIgnoreCase(accType)) {
            new adminDB().setVisible(true);
        } else if ("Customer".equalsIgnoreCase(accType)) {
            new UserDB().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Unknown user type!", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.dispose(); // Close login window
    } else {
        JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        password.requestFocus();
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error during login: " + e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}
  
    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
         login.setBackground(lightGray);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(lightBlue);
    }//GEN-LAST:event_loginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel passtext;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registerbutton;
    private javax.swing.JLabel requiredpass;
    private javax.swing.JLabel requireduser;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
